language: node_js
node_js:
  - '12'
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod --base-href /QuoteManager/
  - mv dist/apps/quote-manager/index.html dist/apps/quote-manager/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/apps/quote-manager
  on:
    branch: master
