language: node_js
node_js:
  - '12'
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - npm install

script:
  - ng build --prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/apps/quote-manager/
  on:
    branch: master
